### ISSUE TITLE
Overloading new/delete is not working in MinGW

### ISSUE THREAD

**Issue by drizt** [adah1972/nvwa#1]
Probably it is not a nvwa problem. But nvwa affects too. So I hope you can help me.

In MinGW application operators new/delete will not be replaced globally. So can't be catched new/delete calls in shared libraries (.dll). new/delete overloading applies only for application .exe file. I tried to ask this on [StackOverflow](https://stackoverflow.com/questions/46025819/global-overload-operator-new-delete-in-mingw) but don't get answer.

**Comment by drizt** [comment]
I wrote minimal [test case](https://github.com/drizt/lib-new-overload). Built it with MinGW and start to see a problem.

**Comment by adah1972** [comment]
I posted an answer on StackOverflow. Hopefully it can help a bit.

**Comment by drizt** [comment]
Thanks.
