### ISSUE TITLE
Do not use static_assert to try and  constrain the types you are developing

### ISSUE THREAD

**Issue by DBJDBJ** [adah1972/nvwa#10]
https://dbj.org/c-foot-gun-with-a-timer/

**Comment by adah1972** [comment]
Not sound advice to me, as `static_assert` gives much better diagnostics—which is very important when other people are not using the template as intended.

**Comment by DBJDBJ** [comment]
`static_assert` is **not** type constraint. "wrong" type can be created if `static_assert` is used only. for example `std::string_view` is not type constrained, it uses only `static_assert`:

```cpp
  // compiles no warnings
   using wrong_type = std::string_view<void ***> ;
```
That is also "not using a template as intended".  The key issue is:

# static_assert does not constrain the type definition

Why do I bother?

**Comment by adah1972** [comment]
What's your point? If you believe my code should not use `static_assert` somewhere, point it out and we can discuss case by case. This is a not a place to discuss abstract coding guidelines.

**Comment by DBJDBJ** [comment]
The key point (to your benefit) is this is not an "abstract coding guideline". 

Managing a project where the programming language (and library based on it) of choice allows planting timebombs is difficult.

One developer very rarely makes a bug. Many developers very often produce many more bugs than one developer. 

Why increasing the risk if you can mitigate it considerably?

Using C++ to develop a core lib, you can dictate type constraints. Do so. As early as possible. 

That is my point :)

ps: Hint. C++20 introduces the new paradigm that is called "constraint" :wink:. If `std::`  started in 2021 you would see type constraints all-around a place.

**Comment by adah1972** [comment]
Please focus on issues.

In case you do not know, I presented on "concepts" as early as 2017.

https://github.com/adah1972/cpp_summit_2017

However, first, they are not really usable in C++17 code; second, `static_assert` is the best when you just want to report a clear failure message (as versus skipping the current overload/specialization, etc.).
