### ISSUE TITLE
debug_new 相关问题

### ISSUE THREAD

**Issue by sandy1219** [adah1972/nvwa#6]
vs2017环境
代码中定义实现了
new相关
1：void* operator new(size_t size);
2：void* operator new[](size_t size);
3：void* operator new(size_t size, const char* file, unsigned int line)
4：void* operator new[](size_t size, const char* file, unsigned int line)
delete相关
1：void operator delete(void* p);
2：void operator delete[](void* p);
3：void* operator new(size_t size, const char* file, unsigned int line);
4：void* operator new[](size_t size, const char* file, unsigned int line);

宏定义了  #define new new(__FILE__,__LINE__)
所以new or new[] 的时候都会调用new 3 api 或者new 4 api
请问一下delete 有啥办法能让代码中delete obj 或者 delete[] obj的时候 自动调用 delete 3 api或者delete 4 api

**Comment by adah1972** [comment]
你理解错了。特殊的 delete 是不需要你手工调用的。即使你用 `operator new(size_t, const char*, unsigned)` 分配的内存，释放也只需要 `operator delete(void*)`。

特殊形式的 `operator delete` 是供构造发生异常时使用的，是编译器自动调用的。你可以参考：

http://wyw.dcweb.cn/leakage.htm

看里面的 Exception in the constructor 那节。

**Comment by sandy1219** [comment]
void* operator new(size_t size, const char* file, unsigned int line) 也是通过宏定义  #define new new(FILE,LINE)  才实现的嘛     我想问下  有没有办法让 delete obj的时候  调用我自定义的 deletefunc(size_t size, const char* file, unsigned int line)  自动把obj 和 文件名 行号 传递过去

**Comment by adah1972** [comment]
delete 是不应该/不可以这么调用的。new 有 placement new，delete 没有——虽然有这样的形式，是供发生异常时编译器自动调用使用的。换个说法，`new("test.cpp", 10) char` 是合法代码，而 `delete("test.cpp", 10) ptr` 是非法代码。
