### ISSUE TITLE
functional里面new的使用没看懂

### ISSUE THREAD

**Issue by yanke1311** [adah1972/nvwa#7]
![image](https://user-images.githubusercontent.com/23717792/79452879-6c706900-801b-11ea-91f0-45dce58f5432.png)
吴老师， 这个new是什么意思呢？是自定义的new吗？

**Comment by adah1972** [comment]
https://en.cppreference.com/w/cpp/language/new#Placement_new
https://zh.cppreference.com/w/cpp/language/new#.E5.B8.83.E7.BD.AE_new

在指针指定的位置进行对象的构造。

**Comment by DBJDBJ** [comment]
If I may intrude :)
```cpp
std::move(*this) ;
```
Leaves the instance in which execution is, aka `this`, in an **undefined** state, as defined in the standard describing[ the behaviour of the std::move](https://herbsutter.com/2020/02/17/move-simply/) ... 

I would love to see object sequence diagram with that operation on it ...

**Comment by adah1972** [comment]
@DBJDBJ This is part of a simplified `optional` implementation. The states are well defined. The line quoted is at line 486 of https://github.com/adah1972/nvwa/blob/master/nvwa/functional.h.

It is inside the `swap` member function, and the line is executed when `this->has_value() && !rhs.has_value()`. So the expected result is `!this->has_value() && rhs.has_value()`. Destructors are called (exactly once) if needed.

**Comment by DBJDBJ** [comment]
I trust you now what are you doing @adah1972 , it is just that
```cpp
std::move(*this) ;
```
Can not be right :)  Sorry for the intrusion.

**Comment by adah1972** [comment]
> I trust you now what are you doing @adah1972 , it is just that
> 
> ```c++
> std::move(*this) ;
> ```
> 
> Can not be right :) Sorry for the intrusion.

Prove it, then. :-)

`std::move(*this)` does not miraculously make _this_ object disappear: it just allows another function to take the value it stores (but still leave it in a destructible state). Generally speaking, you should not do anything except destruction—and maybe reassignment—after it is _moved_. It is then in an _empty_ state. This is what Sutter’s example shows.

In my case, I just happen to intend *this* object to become empty in that specific branch.

`delete this` is not undefined behaviour _per se_, and my code is even safer.

**Comment by DBJDBJ** [comment]
Well me and Sean Parrent (have you seen his comment?)  :) we do not share that point of view with Herb, or Bjarne or Howard H. We can't understand "unspecified state" in the prog lang spec. I agree with your observations but even you use "generally speaking" terminology :)  I would like to see something exact: yes or now. Not maybe. 

Thus when I do use `std::move` I simply use it for "moved from" logic, in which case I consider the moved-from object simply "invalid" after the move.

I trust your lib is good. I was just taken aback with that code.

**Comment by adah1972** [comment]
I believe it is better to understand the *moved-from* state as *uninitialized*, or *empty* state, **not** *invalid*. An object, during its lifetime, should never violate its invariant constraints, even when it is *empty*. Once you separate *empty* from *invalid*, the code will be easy to understand.

Sutter’s case shows undefined behaviour, not because an empty object is invalid, but because dereferencing a null pointer is invalid. My case is similar: an empty `optional` is completely OK, but trying to access the underlying value when the `optional` is empty *would be* undefined behaviour.

**Comment by adah1972** [comment]
Regarding Sean’s comment: The standard does not specify the exact state after an object is moved from, so there is little you can do about such an object. My case is different: I write the `optional` class, and I specify its exact behaviour. For me, it is valid *and specified*: an empty state after being moved from.

**Comment by adah1972** [comment]
Regarding the standard: The standard is like the law, it describes only the very basics. One can always do more than the law says. In my case, I want the moved-from state allows reassignment, but in many cases it may not be necessary: the only operation required to be valid is destruction. It is completely OK for a class to specify that the only allowed operation after being moved from is destruction.

This only means a generic template should not assume much about a third-party class’s move behaviour. It does not mean we cannot assign more semantics to our classes’ move behaviour.
