### ISSUE TITLE
fc_queue疑问

### ISSUE THREAD

**Issue by zhangdexin** [adah1972/nvwa#8]
您好  请教下  fc_queue之前的老接口是咋保证两个线程访问安全的？没太看懂

**Comment by adah1972** [comment]
不能保证：

> Previously the code worked for me, but at least theoretically it was not safe: compilers may optimize the code in unexpected ways, and multiple processors may cause surprises too.

**Comment by adah1972** [comment]
如果指的是老接口的使用 atomic 的新实现，则没有问题。由于这个类的无锁使用只适用于单发单收的情况，纯粹从功能上来说，`write` 相当于先判断 `full` 再 `push`；读这一边，使用老接口的话就是先判断 `empty`，然后使用 `front`，最后 `pop`。

**Comment by zhangdexin** [comment]
谢谢您回复  明白了

**Comment by DBJDBJ** [comment]
Зашто пишете на кинеском?
