### ISSUE TITLE
关于debug_new的IBM中文网中已经找不到中文版本的链接了

### ISSUE THREAD

**Issue by xiaoxiaowesley** [adah1972/nvwa#9]
hi，你好。我对内存泄漏感兴趣。
看了你debug_new这边文章，因为有些内容对我而言有点晦涩，想对比下中文版的文章再对比下。但是
关于的[IBM中文网](https://developer.ibm.com/zh/technologies/linux/)中已经找不到中文版本的链接了。

也想趁宝地再想问下业界有哪些更好的轮子吗？

**Comment by adah1972** [comment]
链接又改了一点点，现在是：

https://www.ibm.com/developerworks/cn/linux/l-mleak2/index.html

通用的 Linux 内存检测，用 Valgrind 就好。

**Comment by asmwarrior** [comment]
上面这个中文链接好像又丢了。。。

**Comment by adah1972** [comment]
没办法，IBM 似乎把网站关了。

用“吴咏炜 一个跨平台的 C++ 内存泄漏检测器”来搜索吧。有不少转载的人。

**Comment by asmwarrior** [comment]
> 没办法，IBM 似乎把网站关了。
> 
> 用“吴咏炜 一个跨平台的 C++ 内存泄漏检测器”来搜索吧。有不少转载的人。

谢谢！

吴大侠，我问个问题，现在内存检测器很多，比如这ssbssa的这个：

[ssbssa/heob: Detects buffer overruns and memory leaks.](https://github.com/ssbssa/heob)

这类检测器，似乎都不是直接修改源代码（类似不是在编译的时候，直接替换new或者delete之类的），而是在程序加载的时候，类似修改和dll中的函数调用表之类的。

你这个是类似于在编译的时候直接替代new或者delete的方法来做的。

能否谈谈两者有什么区别？

因为之前在和ssbssa探讨一个内存泄漏的问题（一个wxWidgets的程序），感觉报告的内存泄漏特别多，但是也不知道是真的报警，还是误报，见：

https://github.com/ssbssa/heob/issues/32#issuecomment-2314412918

还有这个讨论：

https://github.com/GitHubLionel/wxMathPlot/issues/46#issuecomment-2322743349

真没搞明白，一个库里面内存泄漏会有如此多么？

谢谢！

**Comment by adah1972** [comment]
如果你有更简单的工具可用，当然就去用啊。比如，Linux 下用 valgrind 和 ASan，非常简单，还能捕捉一些额外的问题。我这个属于穷人的工具，除了在不现成支持内存泄漏检测工具的环境下能用外，可能也就有点性能上的优势吧。

内存分配不释放永远是可疑的，基本不是误报。当然，有些内存泄漏是一次性的，不会持续泄漏，因此可以说不是真正的问题；甚至有好处，可以让程序退出时减少清理动作。但即使如此，这种问题也会导致内存泄漏检测工具误报，使得捕捉真正的内存泄漏更加困难，因此从工程实践上不可取。很早时 GCC 里有这种“优化”，后来就没了——我估计可能就是这个原因。

**Comment by asmwarrior** [comment]
> 如果你有更简单的工具可用，当然就去用啊。比如，Linux 下用 valgrind 和 ASan，非常简单，还能捕捉一些额外的问题。我这个属于穷人的工具，除了在不现成支持内存泄漏检测工具的环境下能用外，可能也就有点性能上的优势吧。
> 
> 内存分配不释放永远是可疑的，基本不是误报。当然，有些内存泄漏是一次性的，不会持续泄漏，因此可以说不是真正的问题；甚至有好处，可以让程序退出时减少清理动作。但即使如此，这种问题也会导致内存泄漏检测工具误报，使得捕捉真正的内存泄漏更加困难，因此从工程实践上不可取。很早时 GCC 里有这种“优化”，后来就没了——我估计可能就是这个原因。

好的，多谢大牛点拨！

我再仔细琢磨琢磨。
